[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "EWAghmkH9oRqUDUWSQv6Fob8LHyvb3YbHhrnm5R8YtJd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[hooks]
