[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "AizHmamwqLJh8vUUXbBchgPYsstUrYPsXxRVBYmHdL7M"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[hooks]
